/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=WorkerBindings src/worker/env.d.ts` (hash: 5b6bdcc2b1eada59821d24147f97801d)
interface __BaseEnv_WorkerBindings {
	ASSETS: Fetcher;
	VITE_SUPABASE_URL: string;
	VITE_SUPABASE_ANON_KEY: string;
	DEEPSEEK_API_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_SUPABASE_URL" | "VITE_SUPABASE_ANON_KEY" | "DEEPSEEK_API_KEY" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
